# Generated by Django 3.1.5 on 2021-05-17 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210517_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='select_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='auctions.category'),
        ),
    ]
