# Generated by Django 3.1.5 on 2021-05-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction_select_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
