# Generated by Django 3.1.5 on 2021-05-19 07:59

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210518_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[500, 300], upload_to='images/'),
        ),
    ]
