# Generated by Django 3.1.5 on 2021-05-19 16:35

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210519_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[500, 500], upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='subtitle',
            field=models.CharField(max_length=1200),
        ),
    ]
