# Generated by Django 3.1.5 on 2021-06-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210607_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
