# Generated by Django 3.1.5 on 2021-06-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210607_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('sold', 'sold'), ('deleted', 'deleted')], default='active', max_length=7),
        ),
    ]
