# Generated by Django 3.1.5 on 2021-06-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('sold', 'sold')], default='active', max_length=7),
        ),
    ]
