# Generated by Django 3.1.5 on 2021-06-18 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_comment_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commment_auctions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions_comment', to='auctions.auction'),
        ),
    ]
