# Generated by Django 3.1.5 on 2021-06-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_comment_commment_auctions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
    ]
